//! OSM XML Scanner
//!
//! Provides a streaming XML parser for reading OSM data files.

use quick_xml::events::Event;
use quick_xml::Reader;
use std::io::BufRead;

use crate::container::OsmObject;
use crate::types::{
    Bounds, Changeset, ChangesetID, Member, Members, Node, NodeID, Note, Relation, RelationID,
    Tag, Tags, Type, User, UserID, Way, WayID, WayNode, WayNodes,
};

/// Error type for XML scanning
#[derive(Debug, thiserror::Error)]
pub enum XmlError {
    #[error("XML parsing error: {0}")]
    Parse(#[from] quick_xml::Error),
    #[error("Invalid attribute: {0}")]
    InvalidAttribute(String),
    #[error("Scanner closed")]
    Closed,
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Parse int error: {0}")]
    ParseInt(#[from] std::num::ParseIntError),
    #[error("Parse float error: {0}")]
    ParseFloat(#[from] std::num::ParseFloatError),
    #[error("Date parse error: {0}")]
    DateParse(#[from] chrono::ParseError),
}

/// Scanner provides a convenient interface for reading a stream of OSM data
/// from an XML file or reader.
pub struct Scanner<R: BufRead> {
    reader: Reader<R>,
    closed: bool,
    current: Option<OsmObject>,
    err: Option<XmlError>,
}

impl<R: BufRead> Scanner<R> {
    /// Creates a new Scanner to read from the given reader
    pub fn new(reader: R) -> Self {
        let mut xml_reader = Reader::from_reader(reader);
        xml_reader.config_mut().trim_text(true);

        Scanner {
            reader: xml_reader,
            closed: false,
            current: None,
            err: None,
        }
    }

    /// Closes the scanner
    pub fn close(&mut self) {
        self.closed = true;
    }

    /// Advances the Scanner to the next element
    /// Returns true if an object was found, false otherwise
    pub fn scan(&mut self) -> bool {
        if self.closed || self.err.is_some() {
            return false;
        }

        let mut buf = Vec::new();

        loop {
            buf.clear();
            match self.reader.read_event_into(&mut buf) {
                Ok(Event::Start(ref e)) | Ok(Event::Empty(ref e)) => {
                    let name_bytes = e.name();
                    let name_ref = name_bytes.as_ref();
                    let name = String::from_utf8_lossy(name_ref).to_lowercase();

                    // Clone the necessary data before calling parse methods
                    let attrs: Vec<(String, String)> = e
                        .attributes()
                        .flatten()
                        .map(|a| {
                            let key = String::from_utf8_lossy(a.key.as_ref()).to_string();
                            let value = String::from_utf8_lossy(&a.value).to_string();
                            (key, value)
                        })
                        .collect();

                    let is_empty = e.name().as_ref().ends_with(b"/>");

                    let result = match name.as_str() {
                        "bounds" => self.parse_bounds(&attrs),
                        "node" => self.parse_node(&attrs, is_empty),
                        "way" => self.parse_way(&attrs),
                        "relation" => self.parse_relation(&attrs),
                        "changeset" => self.parse_changeset(&attrs),
                        "note" => self.parse_note(&attrs),
                        "user" => self.parse_user(&attrs),
                        _ => continue,
                    };

                    match result {
                        Ok(obj) => {
                            self.current = Some(obj);
                            return true;
                        }
                        Err(e) => {
                            self.err = Some(e);
                            return false;
                        }
                    }
                }
                Ok(Event::Eof) => return false,
                Err(e) => {
                    self.err = Some(XmlError::Parse(e));
                    return false;
                }
                _ => continue,
            }
        }
    }

    /// Returns the most recent object generated by a call to scan
    pub fn object(&self) -> Option<&OsmObject> {
        self.current.as_ref()
    }

    /// Takes ownership of the current object
    pub fn take_object(&mut self) -> Option<OsmObject> {
        self.current.take()
    }

    /// Returns the first error that was encountered
    pub fn err(&self) -> Option<&XmlError> {
        self.err.as_ref()
    }

    fn parse_bounds(&mut self, attrs: &[(String, String)]) -> Result<OsmObject, XmlError> {
        let mut bounds = Bounds::default();

        for (key, value) in attrs {
            match key.as_str() {
                "minlat" => bounds.min_lat = value.parse()?,
                "maxlat" => bounds.max_lat = value.parse()?,
                "minlon" => bounds.min_lon = value.parse()?,
                "maxlon" => bounds.max_lon = value.parse()?,
                _ => {}
            }
        }

        Ok(OsmObject::Bounds(bounds))
    }

    fn parse_node(
        &mut self,
        attrs: &[(String, String)],
        is_empty: bool,
    ) -> Result<OsmObject, XmlError> {
        let mut node = Node::default();

        for (key, value) in attrs {
            match key.as_str() {
                "id" => node.id = NodeID(value.parse()?),
                "lat" => node.lat = value.parse()?,
                "lon" => node.lon = value.parse()?,
                "version" => node.version = value.parse()?,
                "changeset" => node.changeset = ChangesetID(value.parse()?),
                "user" => node.user = value.to_string(),
                "uid" => node.uid = UserID(value.parse()?),
                "visible" => node.visible = value == "true",
                "timestamp" => {
                    node.timestamp = chrono::DateTime::parse_from_rfc3339(value)
                        .map(|dt| dt.with_timezone(&chrono::Utc))?;
                }
                _ => {}
            }
        }

        // Parse child tags if not empty element
        if !is_empty {
            node.tags = self.parse_tags("node")?;
        }

        Ok(OsmObject::Node(node))
    }

    fn parse_way(&mut self, attrs: &[(String, String)]) -> Result<OsmObject, XmlError> {
        let mut way = Way::default();

        for (key, value) in attrs {
            match key.as_str() {
                "id" => way.id = WayID(value.parse()?),
                "version" => way.version = value.parse()?,
                "changeset" => way.changeset = ChangesetID(value.parse()?),
                "user" => way.user = value.to_string(),
                "uid" => way.uid = UserID(value.parse()?),
                "visible" => way.visible = value == "true",
                "timestamp" => {
                    way.timestamp = chrono::DateTime::parse_from_rfc3339(value)
                        .map(|dt| dt.with_timezone(&chrono::Utc))?;
                }
                _ => {}
            }
        }

        // Parse child elements (nd refs and tags)
        let (nodes, tags) = self.parse_way_children()?;
        way.nodes = WayNodes(nodes);
        way.tags = tags;

        Ok(OsmObject::Way(way))
    }

    fn parse_relation(&mut self, attrs: &[(String, String)]) -> Result<OsmObject, XmlError> {
        let mut relation = Relation::default();

        for (key, value) in attrs {
            match key.as_str() {
                "id" => relation.id = RelationID(value.parse()?),
                "version" => relation.version = value.parse()?,
                "changeset" => relation.changeset = ChangesetID(value.parse()?),
                "user" => relation.user = value.to_string(),
                "uid" => relation.uid = UserID(value.parse()?),
                "visible" => relation.visible = value == "true",
                "timestamp" => {
                    relation.timestamp = chrono::DateTime::parse_from_rfc3339(value)
                        .map(|dt| dt.with_timezone(&chrono::Utc))?;
                }
                _ => {}
            }
        }

        // Parse child elements (members and tags)
        let (members, tags) = self.parse_relation_children()?;
        relation.members = Members(members);
        relation.tags = tags;

        Ok(OsmObject::Relation(relation))
    }

    fn parse_changeset(&mut self, attrs: &[(String, String)]) -> Result<OsmObject, XmlError> {
        let mut cs = Changeset::default();

        for (key, value) in attrs {
            match key.as_str() {
                "id" => cs.id = ChangesetID(value.parse()?),
                "user" => cs.user = value.to_string(),
                "uid" => cs.uid = UserID(value.parse()?),
                "open" => cs.open = value == "true",
                "num_changes" => cs.num_changes = value.parse()?,
                "comments_count" => cs.comments_count = value.parse()?,
                "min_lat" => cs.min_lat = value.parse()?,
                "max_lat" => cs.max_lat = value.parse()?,
                "min_lon" => cs.min_lon = value.parse()?,
                "max_lon" => cs.max_lon = value.parse()?,
                "created_at" => {
                    cs.created_at = chrono::DateTime::parse_from_rfc3339(value)
                        .map(|dt| dt.with_timezone(&chrono::Utc))?;
                }
                "closed_at" => {
                    cs.closed_at = chrono::DateTime::parse_from_rfc3339(value)
                        .map(|dt| dt.with_timezone(&chrono::Utc))?;
                }
                _ => {}
            }
        }

        // Parse tags
        cs.tags = self.parse_tags("changeset")?;

        Ok(OsmObject::Changeset(cs))
    }

    fn parse_note(&mut self, attrs: &[(String, String)]) -> Result<OsmObject, XmlError> {
        let mut note = Note::default();

        for (key, value) in attrs {
            match key.as_str() {
                "lat" => note.lat = value.parse()?,
                "lon" => note.lon = value.parse()?,
                _ => {}
            }
        }

        Ok(OsmObject::Note(note))
    }

    fn parse_user(&mut self, attrs: &[(String, String)]) -> Result<OsmObject, XmlError> {
        let mut user = User::default();

        for (key, value) in attrs {
            match key.as_str() {
                "id" => user.id = UserID(value.parse()?),
                "display_name" => user.name = value.to_string(),
                "account_created" => {
                    user.created_at = chrono::DateTime::parse_from_rfc3339(value)
                        .map(|dt| dt.with_timezone(&chrono::Utc))?;
                }
                _ => {}
            }
        }

        Ok(OsmObject::User(user))
    }

    fn parse_tags(&mut self, end_tag: &str) -> Result<Tags, XmlError> {
        let mut tags = Vec::new();
        let mut buf = Vec::new();

        loop {
            buf.clear();
            match self.reader.read_event_into(&mut buf) {
                Ok(Event::Start(ref e)) | Ok(Event::Empty(ref e)) => {
                    let name_bytes = e.name();
                    let name = String::from_utf8_lossy(name_bytes.as_ref()).to_lowercase();

                    if name == "tag" {
                        let mut k = String::new();
                        let mut v = String::new();

                        for attr in e.attributes().flatten() {
                            let key = String::from_utf8_lossy(attr.key.as_ref());
                            let value = String::from_utf8_lossy(&attr.value);

                            match key.as_ref() {
                                "k" => k = value.to_string(),
                                "v" => v = value.to_string(),
                                _ => {}
                            }
                        }

                        tags.push(Tag::new(k, v));
                    }
                }
                Ok(Event::End(ref e)) => {
                    let name = String::from_utf8_lossy(e.name().as_ref()).to_lowercase();
                    if name == end_tag {
                        break;
                    }
                }
                Ok(Event::Eof) => break,
                Err(e) => return Err(XmlError::Parse(e)),
                _ => continue,
            }
        }

        Ok(Tags(tags))
    }

    fn parse_way_children(&mut self) -> Result<(Vec<WayNode>, Tags), XmlError> {
        let mut nodes = Vec::new();
        let mut tags = Vec::new();
        let mut buf = Vec::new();

        loop {
            buf.clear();
            match self.reader.read_event_into(&mut buf) {
                Ok(Event::Start(ref e)) | Ok(Event::Empty(ref e)) => {
                    let name_bytes = e.name();
                    let name = String::from_utf8_lossy(name_bytes.as_ref()).to_lowercase();

                    if name == "nd" {
                        let mut node = WayNode::default();

                        for attr in e.attributes().flatten() {
                            let key = String::from_utf8_lossy(attr.key.as_ref());
                            let value = String::from_utf8_lossy(&attr.value);

                            match key.as_ref() {
                                "ref" => node.id = NodeID(value.parse()?),
                                "lat" => node.lat = value.parse()?,
                                "lon" => node.lon = value.parse()?,
                                _ => {}
                            }
                        }

                        nodes.push(node);
                    } else if name == "tag" {
                        let mut k = String::new();
                        let mut v = String::new();

                        for attr in e.attributes().flatten() {
                            let key = String::from_utf8_lossy(attr.key.as_ref());
                            let value = String::from_utf8_lossy(&attr.value);

                            match key.as_ref() {
                                "k" => k = value.to_string(),
                                "v" => v = value.to_string(),
                                _ => {}
                            }
                        }

                        tags.push(Tag::new(k, v));
                    }
                }
                Ok(Event::End(ref e)) => {
                    let name = String::from_utf8_lossy(e.name().as_ref()).to_lowercase();
                    if name == "way" {
                        break;
                    }
                }
                Ok(Event::Eof) => break,
                Err(e) => return Err(XmlError::Parse(e)),
                _ => continue,
            }
        }

        Ok((nodes, Tags(tags)))
    }

    fn parse_relation_children(&mut self) -> Result<(Vec<Member>, Tags), XmlError> {
        let mut members = Vec::new();
        let mut tags = Vec::new();
        let mut buf = Vec::new();

        loop {
            buf.clear();
            match self.reader.read_event_into(&mut buf) {
                Ok(Event::Start(ref e)) | Ok(Event::Empty(ref e)) => {
                    let name_bytes = e.name();
                    let name = String::from_utf8_lossy(name_bytes.as_ref()).to_lowercase();

                    if name == "member" {
                        let mut member = Member::default();

                        for attr in e.attributes().flatten() {
                            let key = String::from_utf8_lossy(attr.key.as_ref());
                            let value = String::from_utf8_lossy(&attr.value);

                            match key.as_ref() {
                                "type" => {
                                    member.member_type = match value.as_ref() {
                                        "node" => Type::Node,
                                        "way" => Type::Way,
                                        "relation" => Type::Relation,
                                        _ => Type::Node,
                                    };
                                }
                                "ref" => member.ref_ = value.parse()?,
                                "role" => member.role = value.to_string(),
                                _ => {}
                            }
                        }

                        members.push(member);
                    } else if name == "tag" {
                        let mut k = String::new();
                        let mut v = String::new();

                        for attr in e.attributes().flatten() {
                            let key = String::from_utf8_lossy(attr.key.as_ref());
                            let value = String::from_utf8_lossy(&attr.value);

                            match key.as_ref() {
                                "k" => k = value.to_string(),
                                "v" => v = value.to_string(),
                                _ => {}
                            }
                        }

                        tags.push(Tag::new(k, v));
                    }
                }
                Ok(Event::End(ref e)) => {
                    let name = String::from_utf8_lossy(e.name().as_ref()).to_lowercase();
                    if name == "relation" {
                        break;
                    }
                }
                Ok(Event::Eof) => break,
                Err(e) => return Err(XmlError::Parse(e)),
                _ => continue,
            }
        }

        Ok((members, Tags(tags)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[test]
    fn test_parse_node() {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
  <node id="123" lat="51.5" lon="-0.1" version="1" changeset="456" user="test" uid="789" visible="true" timestamp="2021-01-01T00:00:00Z">
    <tag k="name" v="Test Node"/>
  </node>
</osm>"#;

        let cursor = Cursor::new(xml);
        let mut scanner = Scanner::new(cursor);

        assert!(scanner.scan());

        if let Some(OsmObject::Node(node)) = scanner.object() {
            assert_eq!(node.id.0, 123);
            assert_eq!(node.lat, 51.5);
            assert_eq!(node.lon, -0.1);
            assert_eq!(node.tags.find("name"), "Test Node");
        } else {
            panic!("Expected Node");
        }
    }

    #[test]
    fn test_parse_way() {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
  <way id="456" version="1">
    <nd ref="1"/>
    <nd ref="2"/>
    <nd ref="3"/>
    <tag k="highway" v="primary"/>
  </way>
</osm>"#;

        let cursor = Cursor::new(xml);
        let mut scanner = Scanner::new(cursor);

        assert!(scanner.scan());

        if let Some(OsmObject::Way(way)) = scanner.object() {
            assert_eq!(way.id.0, 456);
            assert_eq!(way.nodes.0.len(), 3);
            assert_eq!(way.tags.find("highway"), "primary");
        } else {
            panic!("Expected Way");
        }
    }

    #[test]
    fn test_parse_relation() {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
  <relation id="789" version="1">
    <member type="way" ref="1" role="outer"/>
    <member type="way" ref="2" role="inner"/>
    <tag k="type" v="multipolygon"/>
  </relation>
</osm>"#;

        let cursor = Cursor::new(xml);
        let mut scanner = Scanner::new(cursor);

        assert!(scanner.scan());

        if let Some(OsmObject::Relation(rel)) = scanner.object() {
            assert_eq!(rel.id.0, 789);
            assert_eq!(rel.members.0.len(), 2);
            assert_eq!(rel.tags.find("type"), "multipolygon");
        } else {
            panic!("Expected Relation");
        }
    }

    #[test]
    fn test_parse_bounds() {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
  <bounds minlat="51.0" maxlat="52.0" minlon="-1.0" maxlon="0.0"/>
</osm>"#;

        let cursor = Cursor::new(xml);
        let mut scanner = Scanner::new(cursor);

        assert!(scanner.scan());

        if let Some(OsmObject::Bounds(bounds)) = scanner.object() {
            assert_eq!(bounds.min_lat, 51.0);
            assert_eq!(bounds.max_lat, 52.0);
            assert_eq!(bounds.min_lon, -1.0);
            assert_eq!(bounds.max_lon, 0.0);
        } else {
            panic!("Expected Bounds");
        }
    }
}
